Math Libraries Landing pages
RadeonOpenCompute/ROCm pull request #1940
Opened 2023-03-14 14:59 UTC by MathiasMagnus

2023-03-14 15:15 UTC, saadrahim commented on docs/reference/gpu_libraries/c++_primitives.md
> +- [Changelog](https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/develop/CHANGELOG.md)
What should the order of these be? I know the rocBLAS example had changelog first. Is it best to have the API reference manual first?

2023-03-14 15:20 UTC, saadrahim requested changes
Fix rocBLAS card order as well.

2023-03-16 15:36 UTC, saadrahim submitted a review, later dismissed

2023-03-17 10:20 UTC, MathiasMagnus commented
Rebased.

2023-03-17 13:16 UTC, saadrahim commented on docs/reference/gpu_libraries/blas.md
>  - [Examples](https://github.com/amd/rocm-examples/tree/develop/Libraries/rocBLAS)
Don't include rocBLAS examples for Tensile.

2023-03-17 13:17 UTC, saadrahim commented on docs/reference/gpu_libraries/fft.md
> +- [Examples](https://github.com/amd/rocm-examples/tree/develop/Libraries/rocFFT)
This doesn't exist yet, please remove.

2023-03-17 13:17 UTC, saadrahim commented on docs/reference/gpu_libraries/math.md
> +[Orochi](https://github.com/GPUOpen-LibrariesAndSDKs/Orochi) library.
Intro to the other math lib pages, probably using grid cards.

2023-03-17 13:19 UTC, saadrahim approved these changes
Approved with comments. Please resolve them and merge. 

Or I may merge this late today and comments to PR should be addressed in a later change.

2023-03-17 16:37 UTC, merged