Added support matrices
RadeonOpenCompute/ROCm pull request #1991
Opened 2023-03-24 18:28 UTC by amathews-amd

for docker releases

2023-03-24 21:23 UTC, saadrahim requested changes
Looks good but we should discuss the long term strategy for this page.

2023-03-24 22:34 UTC, amathews-amd commented on docs/release/support_matrix.md
> +
The containers would only be released 1-2 weeks after ROCm 5.6

2023-03-24 22:35 UTC, amathews-amd commented on docs/release/support_matrix.md
> +## ROCm 5.6
We need to keep the info on file for all versions of ROCm that is publicly available.

2023-03-24 22:36 UTC, amathews-amd commented on docs/release/support_matrix.md
> +
cc: @amd-aakash

2023-03-26 02:34 UTC, SamuelMarks commented
Did you also want to document kernel support like on https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4.3/page/About_This_Document.html ?

BTW: I wanted to mess around with 6.2.8 kernel support for my  AMD Radeon™ RX 6850M XT 12GB GDDR6; i.e., Navi22 by hacking around [unofficial] patches referenced from https://github.com/RadeonOpenCompute/ROCm/issues/1668 at https://github.com/xuhuisheng/rocm-build.

2023-03-26 02:39 UTC, SamuelMarks commented
Did you also want to document kernel support like on https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4.3/page/About_This_Document.html ?

BTW: I wanted to mess around with 6.2.8 kernel support for my  AMD Radeon™ RX 6850M XT 12GB GDDR6; i.e., Navi22 by hacking around [unofficial] patches referenced from https://github.com/RadeonOpenCompute/ROCm/issues/1668 at https://github.com/xuhuisheng/rocm-build. - Specifically I want to know what kernel(s) are supported by this new version of ROCm and [offtopic] if you had any tips for porting to the latest kernel.

2023-03-26 13:16 UTC, xuhuisheng commented
@SamuelMarks 
My suggesetion is using upstream kernel of amdgpu version.
Its said that the latest version of kernel had already hold an merged amdgpu-dkms version. If kernel version too new to be supported by ROCm offically, we could use this built-in amdgpu-dkms version directly.

2023-03-26 13:17 UTC, SamuelMarks commented
Thanks @xuhuisheng I'll give that a shot

2023-03-28 14:39 UTC, saadrahim commented on docs/release/support_matrix.md
> +
Need to document process for this step on post release actions.

2023-03-28 14:42 UTC, saadrahim commented
> Did you also want to document kernel support like on https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4.3/page/About_This_Document.html ?
> 
> BTW: I wanted to mess around with 6.2.8 kernel support for my AMD Radeon™ RX 6850M XT 12GB GDDR6; i.e., Navi22 by hacking around [unofficial] patches referenced from #1668 at https://github.com/xuhuisheng/rocm-build. - Specifically I want to know what kernel(s) are supported by this new version of ROCm and [offtopic] if you had any tips for porting to the latest kernel.

@SamuelMarks I won't block this PR to address your concerns. However, #1995 was raised to track this.

2023-03-28 14:44 UTC, saadrahim commented on docs/release/support_matrix.md
> +
Tracked in #1996

2023-03-28 14:44 UTC, saadrahim approved these changes
Concerns tracked separately

2023-03-28 14:45 UTC, merged