Update deep learning guide
RadeonOpenCompute/ROCm pull request #2124
Opened 2023-05-09 15:40 UTC by liligwu

2023-05-09 15:46 UTC, saadrahim commented on docs/how_to/introduction_to_deep_learning_guide.md
> +# Introduction to Deep Learning Guide
This type of introductory content on deep learning is not the suitable for documentation. The assumption is the end user knows what ML is. If not, there are other resources that can help them understand ML.

2023-05-09 15:47 UTC, Rmalavally commented
Typo in Optimization - pull/2124

Have two sections for Training and Inference (rather than Optimization?)

2023-05-09 15:47 UTC, saadrahim commented on docs/how_to/introduction_to_deep_learning_guide.md
> +
This content belongs in amd.com websites outside of documentation. The proper connection is to the marketing team is  being made offline.

2023-05-09 15:53 UTC, saadrahim requested changes
Please pass the markdown linter

2023-05-09 15:53 UTC, saadrahim commented on docs/examples/optimization.md
> +## Optimization
markdown header levels are wrong here. Please pass linting.

2023-05-09 17:55 UTC, liligwu commented on docs/how_to/introduction_to_deep_learning_guide.md
@amathews-amd, what's your comment please?

2023-05-09 17:58 UTC, amathews-amd commented on docs/how_to/introduction_to_deep_learning_guide.md
I am okay if the main content if fully captured.

2023-05-09 18:48 UTC, liligwu commented on docs/examples/optimization.md
> +    ```py
syntax highlights corrected.

2023-05-09 18:48 UTC, liligwu commented on docs/examples/optimization.md
> +    ```py
syntax highlights corrected.

2023-05-10 13:19 UTC, saadrahim commented on docs/examples/troubleshooting.md
> +**Q: Which consumer GPUs does ROCm support?**
Please remove this. section

2023-05-10 15:03 UTC, liligwu commented on docs/examples/troubleshooting.md
> +**Q: Can I run ROCm on Windows?**
removed

2023-05-10 15:05 UTC, liligwu commented on docs/examples/troubleshooting.md
> +**Q: Which consumer GPUs does ROCm support?**
removed

2023-05-10 19:32 UTC, saadrahim commented on docs/examples/optimization.md
> +- [Use the ROCm build tool](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX#use-the-rocm-build-tool-rbuild) - This approach uses [rbuild](https://github.com/RadeonOpenCompute/rbuild) to install t
Please ignore the last comment.

2023-05-10 21:20 UTC, liligwu commented
@saadrahim. Would you please merge the PR if there would be no more comments? Thank you.

2023-05-10 22:25 UTC, saadrahim commented
> @saadrahim. Would you please merge the PR if there would be no more comments? Thank you.

Hi Li,
There are still changes I would like to see. I don't need your contribution on the changes. I need to find a writer with sufficient time to add the functionality. As an example, the document name and nav organization structure of the your commit needs revision. This should be in by early next week.

2023-05-24 18:37 UTC, Naraenda commented
@saadrahim Hi! Please re-review:
- Rebased due to conflicting changes.
- Uses footnotes for references.
  - Also removed `references.md`.
- Renamed "Examples" to "Tutorials & Examples" in TOC.
- Uses `all.md` filenames as is common with other directories.
- Converted machine learning landing page to grids.
- Minor markup improvements.

2023-05-24 19:54 UTC, saadrahim approved these changes

2023-05-24 21:42 UTC, saadrahim approved these changes

2023-05-24 22:04 UTC, saadrahim approved these changes

2023-05-24 22:04 UTC, merged