Adding openmp image
RadeonOpenCompute/ROCm pull request #2323
Opened 2023-07-14 06:46 UTC by SwRaw

2023-07-14 17:28 UTC, samjwu submitted a review, later dismissed

2023-07-14 17:29 UTC, samjwu commented
https://advanced-micro-devices-demo--2323.com.readthedocs.build/en/2323/reference/openmp/openmp.html

2023-07-14 21:14 UTC, keryell commented
Would it be possible to have `git` friendly formats instead of binaries.
A vector format would be event better.
What about SVG?

2023-07-14 21:27 UTC, Rmalavally commented
@keryell Thank you for your feedback. Let me check and get back to you.

2023-07-17 13:50 UTC, Rmalavally approved these changes

2023-07-17 14:17 UTC, saadrahim requested changes

2023-07-17 14:17 UTC, saadrahim commented on docs/data/reference/openmp/openmp_toolchain.jpg
The jpg file should likely be deleted if we can use just the svg.

2023-07-17 14:19 UTC, Rmalavally commented on docs/data/reference/openmp/openmp_toolchain.jpg
That's right. 

@SwRaw Could you please delete the jpg file? Thanks so much.

2023-07-17 15:50 UTC, samjwu commented on docs/data/reference/openmp/openmp_toolchain.jpg
Done in [5321e2e](https://github.com/RadeonOpenCompute/ROCm/pull/2323/commits/5321e2ee3e463cd55eec599dc7f689d317f55ffc)

2023-07-25 17:04 UTC, saadrahim approved these changes

2023-07-25 17:05 UTC, merged