What-is and TOC clean-up
RadeonOpenCompute/ROCm pull request #2539
Opened 2023-10-10 23:03 UTC by LisaDelaney

2023-10-11 17:53 UTC, Rmalavally commented on docs/sphinx/_toc.yml.in
>            title: ROCm validation suite
ROCm Validation Suite is not a library. Perhaps move it to Install?  

@LisaDelaney

2023-10-11 17:54 UTC, Rmalavally commented on docs/sphinx/_toc.yml.in
> +          title: ROCProfiler
Move ROCProfiler and ROCTracer under Tools for ease of access? @LisaDelaney

2023-10-11 17:55 UTC, Rmalavally commented on docs/what-is-rocm.md
>  | [ROCm Data Center Tool](https://rocm.docs.amd.com/projects/rdc/en/latest/) | Simplifies administration and addresses key infrastructure challenges in AMD GPUs in cluster and data-center environment
Also under ROCm Tools @LisaDelaney

2023-10-11 17:56 UTC, Rmalavally commented on docs/what-is-rocm.md
> +| Project | Description |
These are not projects but libraries. Do we want to rename this to Libraries?

2023-10-11 20:48 UTC, Rmalavally commented on docs/what-is-rocm.md
>  | [ROCm Data Center Tool](https://rocm.docs.amd.com/projects/rdc/en/latest/) | Simplifies administration and addresses key infrastructure challenges in AMD GPUs in cluster and data-center environment
Sounds good, Lisa. Previously, we have had rocPRIM with other Math and Communication Libraries. You could consider moving it under Reference/Libraries.

@LisaDelaney

2023-10-12 21:21 UTC, saadrahim requested changes

2023-10-12 21:21 UTC, saadrahim commented on docs/what-is-rocm.md
> +| [ROCdbgapi](https://rocm.docs.amd.com/projects/ROCdbgapi/en/latest/) | The ROCm debugger library |
```suggestion
| [ROCdbgapi](https://rocm.docs.amd.com/projects/ROCdbgapi/en/latest/) | The ROCm debugger API library |
```

2023-10-16 17:15 UTC, saadrahim submitted a review, later dismissed

2023-10-16 17:20 UTC, saadrahim commented on docs/sphinx/_toc.yml.in
> +        - url: https://rocm.docs.amd.com/projects/rocPRIM/en/latest/index.html
if the version of ROCm changes, these links will always point to latest.

2023-10-16 21:24 UTC, saadrahim approved these changes

2023-10-16 21:25 UTC, merged